name: module4_task0
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-18.04 
    steps:
      - uses: actions/checkout@v3
      - run: cd module4_task0 && sudo ./setup.sh
      - run: cd module4_task0 && make build
      - run: cd module4_task0 && make help
      - run: cd module4_task0 && post POST_NAME=name POST_TITLE=title
      - run: cd module4_task0 && make clean
